#!/bin/bash

# example: ./i18n_create simple_daemon ru

CURRENT_DIR=`pwd`

cd venv
source bin/activate
cd ..
mkdir locale
cd locale
mkdir $2
cd $2
mkdir LC_MESSAGES
cd $CURRENT_DIR
pygettext -a -v -d $1 -p locale/$2/LC_MESSAGES/ *.py utils/*.py utils/api/*.py utils/scanners/*.py
deactivate
