#!/bin/bash

rm -rf venv
mkdir venv
virtualenv --python=python3.5 venv
cd venv
source bin/activate
echo -ne "\n"
pip install -U -r ../venv_requirements.txt
echo -ne "\n"
pip list --format=columns > ../venv_installed.txt
deactivate
